apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: your-dockerhub-username/fastapi:v14
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: your-dockerhub-username/flask:v14
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etl
  template:
    metadata:
      labels:
        app: etl
    spec:
      containers:
      - name: etl
        image: your-dockerhub-username/fastapi:v14
        command: ["uvicorn", "fastapi_service.main:app", "--host", "0.0.0.0", "--port", "8100"]
        ports:
        - containerPort: 8100
        env:
        - name: PORT
          value: "8100"

---
apiVersion: v1
kind: Service
metadata:
  name: etl-service
spec:
  selector:
    app: etl
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
  type: ClusterIP
