services:
  fastapi:
    build:
      context: ./api
      dockerfile: fastapi/Dockerfile
    ports:
      - "8000:8000"

  flask:
    build:
      context: ./api
      dockerfile: flask/Dockerfile
    ports:
      - "8001:5000"
