services:
  fastapi:
    build:
      context: ./api
      dockerfile: fastapi_service/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api/fastapi_service:/app/fastapi_service
    command: uvicorn fastapi_service.main:app --host 0.0.0.0 --port 8000 --reload
