services:
  fastapi:
    build: ./api/fastapi
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./api/fastapi:/app   # mount local code
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
