docker_compose('docker-compose.yml')

local_resource(
    'web-restart',
    cmd='docker compose restart web',
    deps=['./versions', './index.html', './style.css', './js']
)

local_resource(
    'fastapi-pip-update',
    cmd='docker compose exec fastapi pip install -r /app/fastapi_service/requirements.txt',
    deps=['./api/fastapi_service/requirements.txt']
)

local_resource(
    'flask-pip-update',
    cmd='docker compose exec flask pip install -r /app/flask_service/requirements.txt',
    deps=['./api/flask_service/requirements.txt']
)
